export default [
    // { type: 'text', author: 'VOIX', data: { text: "Les Aventures de Sophie Pétoncule, épisode cinquième. « Sophie chez le psychologue »." } },
    // { type: 'text', author: 'VOIX', data: { text: "(Le psychologue ouvre la porte et laisse entrer Sophie Pétoncule.)" } },
    { type: 'text', author: 'psychologue', data: { text: "Par ici, je vous en prie…" } },
    { type: 'text', author: 'me', data: { text: "Mais arrêtez de regarder mes fesses, c’est personnel les fesses…" } },
    { type: 'text', author: 'psychologue', data: { text: "Asseyez-vous. Est-ce que vous pouvez me dire en quelques mots pourquoi vous venez voir un psychanalyste ?" } },
    { type: 'text', author: 'me', data: { text: "Ah non… moi je viens pas pour vous voir, je viens pour vous parler." } },
    { type: 'text', author: 'psychologue', data: { text: "Bien, je vais vous demander de vous allonger sur ce divan…" } },
    { type: 'text', author: 'me', data: { text: "Ah bon, bon, ben, je suis d’accord pour m’allonger mais à une condition, c’est que vous me donnez un oreiller, une couverture et une tututte, sinon, j’arriverai jamais à m’endormir." } },
    { type: 'text', author: 'psychologue', data: { text: "Vous n’êtes pas là pour dormir mademoiselle, allongez-vous." } },
    { type: 'text', author: 'me', data: { text: "Oh là là c’est chiant, tout ce trajet… Mais arrêtez de regarder mes fesses, c’est personnel les fesses, tu peux regarder mes nichons si tu veux…" } },
    { type: 'text', author: 'psychologue', data: { text: "Allongez-vous. Apparemment, c’est votre première analyse…" } },
    // { type: 'text', author: 'VOIX', data: { text: "la tête dans le lit" } },
    { type: 'text', author: 'me', data: { text:"Beu hfeu bouhou feuh feuh."}},
    { type: 'text', author: 'psychologue', data: { text: "Retournez-vous. Je disais donc qu’apparemment c’est votre première analyse…" } },
    { type: 'text', author: 'me', data: { text: "Ah non, alors là, désolée, mais c’est pas du tout la première analyse, un jour j’ai fait pipi dans un flacon." } },
    { type: 'text', author: 'psychologue', data: { text: "Hum hum… Parlez-moi de votre mère…" } },
    { type: 'text', author: 'me', data: { text: "Ah non, désolée, mais si je viens ici et que je vous paie et tout, c’est pour parler de moi, pas pour parler de quelqu’un d’autre que moi. Si tu veux parler de ma mère t’as qu’à l’appeler…" } },
    { type: 'text', author: 'psychologue', data: { text: "Vous savez c’est quand même important, parlez-moi de vos géniteurs." } },
    { type: 'text', author: 'me', data: { text: "Attendez, bon bah il faut savoir que je suis très pudique alors je refuse de parler de mon appareil géniteur, je suis pas chez mon génitologue quand même…" } },
    // { type: 'text', author: 'VOIX', data: { text: "(Elle se rallonge.)" } },
    { type: 'text', author: 'me', data: { text: "Aïe." } },
    { type: 'text', author: 'psychologue', data: { text: "Hum hum… Racontez-moi votre rêve." } },
    { type: 'text', author: 'me', data: { text: "Mon rêve, ce serait d’avoir six fois la même robe, comme ça, je pourrais en mettre une propre tous les jours, parce que bon, ben faut savoir que le dimanche, j’ai pas besoin de robe, parce que le dimanche, je m’habille toute nue." } },
    { type: 'text', author: 'psychologue', data: { text: "Une fois de plus, on s’est pas compris, je voudrais que vous me racontiez le rêve que vous avez eu la nuit dernière." } },
    { type: 'text', author: 'me', data: { text: "Ah ben, non, la nuit dernière, j’ai pas rêvé, j’ai dormi. Aïe." } },
    // { type: 'text', author: 'VOIX', data: { text: "(Elle se rallonge.)" } },
    { type: 'text', author: 'me', data: { text: "Aïe." } },
    { type: 'text', author: 'psychologue', data: { text: "Ma première impression, mademoiselle, c’est qu’il y a chez vous une altération assez nette de votre compréhension…" } },
    { type: 'text', author: 'me', data: { text: "Alors là, moi, j’ai rien compris à cette phrase." } },
    { type: 'text', author: 'psychologue', data: { text: "Revenons à votre robe. La robe semble tenir une place très importante dans votre vie…" } },
    { type: 'text', author: 'me', data: { text: "Oui oui." } },
    { type: 'text', author: 'psychologue', data: { text: "Alors à quoi ça vous fait penser, une robe…?" } },
    { type: 'text', author: 'me', data: { text: "Bon, ben, moi, une robe ça me fait penser à une jupe mais avec un haut qui serait attaché." } },
    { type: 'text', author: 'psychologue', data: { text: "Mademoiselle, je vous arrête…" } },
    { type: 'text', author: 'me', data: { text: "Ah bon, et je peux savoir pourquoi vous m’arrêtez, vu que j’ai jamais commis de meurtre, sauf une fourmi, mais c’était même pas moi, c’est mon pied qui l’a écrasée ?" } },
    // { type: 'text', author: 'VOIX', data: { text: "(Elle se rallonge.)" } },
    { type: 'text', author: 'me', data: { text: "Aïe." } },
    { type: 'text', author: 'psychologue', data: { text: "Bien, on va dire que la séance est terminée…" } },
    { type: 'text', author: 'me', data: { text: "Ah bon, eh ben elle était un tout petit peu pourrie cette séance, vu que j’ai même pas eu de pop-corn et en plus j’ai même pas vu de film, rien, même pas un petit générique…" } },
    { type: 'text', author: 'psychologue', data: { text: "T’es vraiment trop conne…" } },
    { type: 'text', author: 'me', data: { text: "Ben toi aussi, vous êtes con. Je fais quoi maintenant ? Je fais quoi maintenant ?" } },
    { type: 'text', author: 'psychologue', data: { text: "Tu te casses." } }
]